header_pages:
  - About.markdown
  - CV.markdown
  - Publications.markdown

title: Gengzhi Yang's Homepage
email: genzyang17@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the webpage of Genz.
baseurl: "" # the subpath of your site, e.g. /blog
url: "Genz17.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: Genz17
# Build settings
theme: minima
#remote_theme: benbalter/retlab
#remote_theme: http[s]://github.<Enterprise>.com/benbalter/retlab
markdown: kramdown
minima:
  skin: solarize
plugins:
  - jekyll-feed
  #- jekyll-remote-theme

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

